#!/bin/bash
# =============================================================================
# Artifactory PostgreSQL 连接修复脚本
# =============================================================================
# 修复两个问题:
# 1. system.yaml 中 PostgreSQL 端口错误 (5432 → 5433)
# 2. pg_hba.conf 未允许 Docker 容器网络连接
#
# 用法: sudo bash fix_artifactory_db.sh
# =============================================================================

set -e

ARTIFACTORY_CONFIG_DIR="/home/zs/DeployAgent/deploy/config/artifactory"
SYSTEM_YAML="$ARTIFACTORY_CONFIG_DIR/system.yaml"
SYSTEM_YAML_NEW="$ARTIFACTORY_CONFIG_DIR/system.yaml.new"

# 确定 PostgreSQL 版本和配置路径
PG_VERSION=$(pg_lsclusters | grep online | awk '{print $1}' | head -1)
PG_CLUSTER=$(pg_lsclusters | grep online | awk '{print $2}' | head -1)
PG_PORT=$(pg_lsclusters | grep online | awk '{print $3}' | head -1)
PG_CONF_DIR="/etc/postgresql/${PG_VERSION}/${PG_CLUSTER}"
PG_HBA_CONF="${PG_CONF_DIR}/pg_hba.conf"

echo "=== PostgreSQL 信息 ==="
echo "  版本: $PG_VERSION"
echo "  集群: $PG_CLUSTER"
echo "  端口: $PG_PORT"
echo "  配置目录: $PG_CONF_DIR"
echo ""

# 获取 Docker 网络网关 IP
DOCKER_GATEWAY=$(docker network inspect devopsagent-network -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' 2>/dev/null || echo "172.18.0.1")
DOCKER_SUBNET=$(docker network inspect devopsagent-network -f '{{range .IPAM.Config}}{{.Subnet}}{{end}}' 2>/dev/null || echo "172.18.0.0/16")
echo "  Docker 网关: $DOCKER_GATEWAY"
echo "  Docker 子网: $DOCKER_SUBNET"
echo ""

# ─── 1. 替换 system.yaml ───
echo "=== 步骤 1: 更新 system.yaml (端口 $PG_PORT) ==="
if [[ -f "$SYSTEM_YAML_NEW" ]]; then
    # 使用预先准备好的新文件，但替换端口为实际端口
    cp "$SYSTEM_YAML_NEW" "$SYSTEM_YAML"
    # 确保端口正确
    sed -i "s/:5432\//:${PG_PORT}\//" "$SYSTEM_YAML"
    sed -i "s/:5433\//:${PG_PORT}\//" "$SYSTEM_YAML"
    chmod 600 "$SYSTEM_YAML"
    rm -f "$SYSTEM_YAML_NEW"
    echo "✓ system.yaml 已更新 (PostgreSQL 端口: $PG_PORT)"
else
    # 直接生成
    cat > "$SYSTEM_YAML" << EOF
## Artifactory system.yaml - Auto-generated by DevOpsAgent
## Artifactory 7.x 强制要求 PostgreSQL, 不再支持 Derby
## PostgreSQL ${PG_VERSION} cluster is on port ${PG_PORT}

shared:
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://${DOCKER_GATEWAY}:${PG_PORT}/artifactory
    username: artifactory
    password: artifactory_secret
EOF
    chmod 600 "$SYSTEM_YAML"
    echo "✓ system.yaml 已生成 (PostgreSQL 端口: $PG_PORT)"
fi

cat "$SYSTEM_YAML"
echo ""

# ─── 2. 配置 pg_hba.conf ───
echo "=== 步骤 2: 配置 pg_hba.conf ==="

# 检查是否已有 Docker 网络的条目
if grep -q "172\.18\.0\.0/16" "$PG_HBA_CONF" 2>/dev/null; then
    echo "✓ pg_hba.conf 已包含 172.18.0.0/16 条目，跳过"
else
    # 添加 Docker 网络允许连接的条目
    echo "" >> "$PG_HBA_CONF"
    echo "# Allow Docker containers (devopsagent-network) to connect" >> "$PG_HBA_CONF"
    echo "host    artifactory    artifactory    172.18.0.0/16    md5" >> "$PG_HBA_CONF"
    echo "✓ pg_hba.conf 已添加 Docker 网络条目"
fi

echo ""
echo "当前 pg_hba.conf 中与 artifactory 相关的条目:"
grep -v "^#" "$PG_HBA_CONF" | grep -v "^$" | grep -i "artifactory\|172\.18"
echo ""

# ─── 3. 确保 listen_addresses = '*' ───
echo "=== 步骤 3: 检查 listen_addresses ==="
PG_CONF="${PG_CONF_DIR}/postgresql.conf"
CURRENT_LISTEN=$(grep "^listen_addresses" "$PG_CONF" 2>/dev/null | awk '{print $3}' | tr -d "'")
if [[ "$CURRENT_LISTEN" == "*" ]]; then
    echo "✓ listen_addresses = '*' 已配置"
else
    echo "当前 listen_addresses = $CURRENT_LISTEN, 修改为 '*'"
    sed -i "s/^#\?listen_addresses.*/listen_addresses = '*'/" "$PG_CONF"
    echo "✓ listen_addresses 已修改为 '*'"
fi

# ─── 4. 重启 PostgreSQL ───
echo ""
echo "=== 步骤 4: 重启 PostgreSQL ==="
systemctl restart postgresql
sleep 2

# 验证
if ss -tlnp | grep -q ":${PG_PORT}"; then
    LISTEN_ADDR=$(ss -tlnp | grep ":${PG_PORT}" | head -1 | awk '{print $4}')
    echo "✓ PostgreSQL 正在监听: $LISTEN_ADDR"
else
    echo "✗ PostgreSQL 未在端口 $PG_PORT 上监听!"
    exit 1
fi

# ─── 5. 验证连接 ───
echo ""
echo "=== 步骤 5: 验证数据库连接 ==="

# 从主机验证
if PGPASSWORD=artifactory_secret psql -h 127.0.0.1 -p "$PG_PORT" -U artifactory -d artifactory -c "SELECT 1;" >/dev/null 2>&1; then
    echo "✓ 本地连接成功 (127.0.0.1:$PG_PORT)"
else
    echo "✗ 本地连接失败!"
fi

# 从 Docker 网关验证
if PGPASSWORD=artifactory_secret psql -h "$DOCKER_GATEWAY" -p "$PG_PORT" -U artifactory -d artifactory -c "SELECT 1;" >/dev/null 2>&1; then
    echo "✓ Docker 网关连接成功 ($DOCKER_GATEWAY:$PG_PORT)"
else
    echo "✗ Docker 网关连接失败! 检查 pg_hba.conf"
    echo "  提示: 确认 pg_hba.conf 包含:"
    echo "  host    artifactory    artifactory    172.18.0.0/16    md5"
fi

echo ""
echo "=== 修复完成 ==="
echo "现在可以重新创建 Artifactory 容器:"
echo "  cd /home/zs/DeployAgent/deploy"
echo "  sudo python3 deploy_all.py --deploy-artifactory-standalone"
